### ISSUE TITLE
can't retrieve incidents - context deadline exceeded

### ISSUE THREAD

**Issue by Mahanotrahul** [metalmatze/digitalocean_exporter#14]
Hi, I am running the do exporter as a docker container. I can see some metrics on /metrics page. But there are warnings reported in the logs. 
I am using the metalmatze/digitalocean_exporter:0.6.1 docker image
```
$ sudo docker logs -f --tail 1 digitalocean_exporter
level=warn ts=2020-10-08T10:51:55.130314947Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:52:10.129703669Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:52:10.12987051Z caller=snapshot.go:61 msg="can't list snapshots" err="Get \"https://api.digitalocean.com/v2/snapshots\": context deadline exceeded"
level=warn ts=2020-10-08T10:52:25.130035769Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:52:25.130147046Z caller=snapshot.go:61 msg="can't list snapshots" err="Get \"https://api.digitalocean.com/v2/snapshots\": context deadline exceeded"
level=warn ts=2020-10-08T10:52:40.12954981Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:52:55.12995342Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:52:55.129958578Z caller=snapshot.go:61 msg="can't list snapshots" err="Get \"https://api.digitalocean.com/v2/snapshots\": context deadline exceeded"
level=warn ts=2020-10-08T10:53:10.130054868Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:53:25.130195926Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:53:40.130741997Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=warn ts=2020-10-08T10:53:55.130038935Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
```
Sometimes, these error too comes up
```
digitalocean_exporter    | level=warn ts=2020-10-08T11:05:55.129682229Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
digitalocean_exporter    | level=warn ts=2020-10-08T11:05:55.129685665Z caller=key.go:56 msg="can't list keys" err="Get \"https://api.digitalocean.com/v2/account/keys\": context deadline exceeded"
digitalocean_exporter    | level=warn ts=2020-10-08T11:05:55.129733339Z caller=droplet.go:99 msg="can't list droplets" err="Get \"https://api.digitalocean.com/v2/droplets\": context deadline exceeded"
digitalocean_exporter    | level=warn ts=2020-10-08T11:05:55.129936014Z caller=image.go:56 msg="can't list images" err="Get \"https://api.digitalocean.com/v2/images?private=true\": context deadline exceeded"
digitalocean_exporter    | panic: runtime error: invalid memory address or nil pointer dereference
digitalocean_exporter    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7ed071]
digitalocean_exporter    | 
digitalocean_exporter    | goroutine 746 [running]:
digitalocean_exporter    | github.com/metalmatze/digitalocean_exporter/collector.(*DropletCollector).Collect(0xc000062cc0, 0xc0002683c0)
digitalocean_exporter    |      /go/src/github.com/metalmatze/digitalocean_exporter/collector/droplet.go:111 +0x1b1
digitalocean_exporter    | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
digitalocean_exporter    |      /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x1a2
digitalocean_exporter    | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
digitalocean_exporter    |      /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe8e
digitalocean_exporter exited with code 2
```

I did a curl inside the container - 
```
/ # apk add curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
....
/ # curl https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json
^C
/ # curl https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json -v
*   Trying 13.236.8.151:443...
* Connected to s2k7tnzlhrpw.statuspage.io (13.236.8.151) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
```
There's no output and it gets stuck there. However, I am able to curl other urls or even curl from host to this url - https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json and get the output. I am not sure why this url is being used (must be used to get metrics info) but it is not able to reach from inside the container.

**Comment by circa10a** [comment]
I wrote the code that fetches incidents. That URL being used is the API endpoint that reports active incidents. The exporter calls it, parses incidents, then reports each incident as a metric. I'm unable to reproduce the context deadline issue. Sounds like you may have an unstable connection.

**Comment by circa10a** [comment]
@Mahanotrahul any updates?

**Comment by circa10a** [comment]
Closing due to lack of response
