### ISSUE TITLE
Unexpected EOF when fetching data from DO's API

### ISSUE THREAD

**Issue by bheisig** [metalmatze/digitalocean_exporter#23]
First of all I want to thank you for maintaining this project. I really appreciate your work.

Unfortunately, this exporter stopped working a few weeks ago. I run your pre-built container image in latest version `0.6.1`. These are the last lines from the log when the container starts:

~~~
digitalocean_exporter_1  | goroutine 848 [running]:
digitalocean_exporter_1  | github.com/metalmatze/digitalocean_exporter/collector.(*DropletCollector).Collect(0xc0000ae420, 0xc0002c4060)
digitalocean_exporter_1  |      /go/src/github.com/metalmatze/digitalocean_exporter/collector/droplet.go:111 +0x1b1
digitalocean_exporter_1  | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
digitalocean_exporter_1  |      /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x1a2
digitalocean_exporter_1  | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
digitalocean_exporter_1  |      /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:454 +0x5ce
digitalocean_exporter_1  | level=info ts=2022-11-09T05:03:19.58640215Z caller=main.go:74 msg="starting digitalocean_exporter" version=0.6.1 revision=60ab0b6a7c5fac17f003e1df01a0c45639682945 buildDate=2020-09-29T10:18:22+0000 goVersion=go1.15.2
digitalocean_exporter_1  | level=info ts=2022-11-09T05:03:19.587319196Z caller=main.go:124 msg=listening addr=:9212
digitalocean_exporter_1  | level=warn ts=2022-11-09T12:03:23.583874406Z caller=snapshot.go:61 msg="can't list snapshots" err="Get \"https://api.digitalocean.com/v2/snapshots\": context deadline exceeded"
digitalocean_exporter_1  | level=info ts=2022-11-09T13:08:47.888274687Z caller=main.go:74 msg="starting digitalocean_exporter" version=0.6.1 revision=60ab0b6a7c5fac17f003e1df01a0c45639682945 buildDate=2020-09-29T10:18:22+0000 goVersion=go1.15.2
digitalocean_exporter_1  | level=info ts=2022-11-09T13:08:47.888811646Z caller=main.go:124 msg=listening addr=:9212
digitalocean_exporter_1  | level=warn ts=2022-11-09T14:47:29.687711412Z caller=droplet.go:99 msg="can't list droplets" err="unexpected EOF"
digitalocean_exporter_1  | panic: runtime error: invalid memory address or nil pointer dereference
digitalocean_exporter_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7ed071]
digitalocean_exporter_1  | 
digitalocean_exporter_1  | goroutine 175 [running]:
digitalocean_exporter_1  | github.com/metalmatze/digitalocean_exporter/collector.(*DropletCollector).Collect(0xc000212360, 0xc000212060)
digitalocean_exporter_1  |      /go/src/github.com/metalmatze/digitalocean_exporter/collector/droplet.go:111 +0x1b1
digitalocean_exporter_1  | github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
digitalocean_exporter_1  |      /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:443 +0x1a2
digitalocean_exporter_1  | created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
digitalocean_exporter_1  |      /go/pkg/mod/github.com/prometheus/client_golang@v1.2.1/prometheus/registry.go:535 +0xe8e
digitalocean_exporter_1  | level=info ts=2022-11-09T14:47:30.35509065Z caller=main.go:74 msg="starting digitalocean_exporter" version=0.6.1 revision=60ab0b6a7c5fac17f003e1df01a0c45639682945 buildDate=2020-09-29T10:18:22+0000 goVersion=go1.15.2
digitalocean_exporter_1  | level=info ts=2022-11-09T14:47:30.355694664Z caller=main.go:124 msg=listening addr=:9212
digitalocean_exporter_1  | level=info ts=2022-11-09T15:21:41.646456507Z caller=main.go:74 msg="starting digitalocean_exporter" version=0.6.1 revision=60ab0b6a7c5fac17f003e1df01a0c45639682945 buildDate=2020-09-29T10:18:22+0000 goVersion=go1.15.2
digitalocean_exporter_1  | level=info ts=2022-11-09T15:21:41.647105552Z caller=main.go:124 msg=listening addr=:9212
digitalocean_exporter_1  | level=info ts=2022-11-09T15:38:49.037905583Z caller=main.go:74 msg="starting digitalocean_exporter" version=0.6.1 revision=60ab0b6a7c5fac17f003e1df01a0c45639682945 buildDate=2020-09-29T10:18:22+0000 goVersion=go1.15.2
digitalocean_exporter_1  | level=info ts=2022-11-09T15:38:49.038667044Z caller=main.go:124 msg=listening addr=:9212
digitalocean_exporter_1  | level=info ts=2022-11-09T15:41:39.928618869Z caller=main.go:74 msg="starting digitalocean_exporter" version=0.6.1 revision=60ab0b6a7c5fac17f003e1df01a0c45639682945 buildDate=2020-09-29T10:18:22+0000 goVersion=go1.15.2
digitalocean_exporter_1  | level=info ts=2022-11-09T15:41:39.929420254Z caller=main.go:124 msg=listening addr=:9212
~~~

As you can see in the snippet from the `docker-compose.yml` the exporter has access to the API via HTTP proxy:

~~~ {.yaml}
---
version: "3.8"

services:
  digitalocean_exporter:
    image: metalmatze/digitalocean_exporter:0.6.1
    restart: always
    environment:
      DIGITALOCEAN_TOKEN: changeme
      http_proxy: {{ http_proxy }}
      https_proxy: {{ http_proxy }}
~~~

I already double-checked if the container can reach the API.

Also, the used token has *not* been expired and has read access to DO's API.

Do you need any other information?

Thanks in advance.
Ben

**Comment by circa10a** [comment]
Hmmm. I'm unable to reproduce this. Can you try running it locally or somewhere that doesn't need to go through a proxy?

**Comment by bheisig** [comment]
Well, I also can't reproduce it anymore. Maybe it's caused by unrelated networking issues… It's happening from time to time on 3 different hosts over the past weeks. When it happens the logs are all the same starting with:

~~~
digitalocean_exporter_1  | level=warn ts=2022-11-06T18:38:45.961033384Z caller=incidents.go:104 msg="can't retrieve incidents" err="Get \"https://s2k7tnzlhrpw.statuspage.io/api/v2/summary.json\": EOF"
digitalocean_exporter_1  | level=warn ts=2022-11-06T18:38:45.961069007Z caller=account.go:75 msg="can't get account" err="Get \"https://api.digitalocean.com/v2/account\": unexpected EOF"
digitalocean_exporter_1  | level=warn ts=2022-11-06T18:38:45.961120416Z caller=volume.go:55 msg="can't list volumes" err="Get \"https://api.digitalocean.com/v2/volumes\": unexpected EOF"
digitalocean_exporter_1  | level=warn ts=2022-11-06T18:38:45.961141839Z caller=droplet.go:99 msg="can't list droplets" err="Get \"https://api.digitalocean.com/v2/droplets\": unexpected EOF"
digitalocean_exporter_1  | level=warn ts=2022-11-06T18:38:45.961140882Z caller=key.go:56 msg="can't list keys" err="Get \"https://api.digitalocean.com/v2/account/keys\": unexpected EOF"
digitalocean_exporter_1  | level=warn ts=2022-11-06T18:38:45.961170163Z caller=snapshot.go:61 msg="can't list snapshots" err="Get \"https://api.digitalocean.com/v2/snapshots\": unexpected EOF"
digitalocean_exporter_1  | panic: runtime error: invalid memory address or nil pointer dereference
digitalocean_exporter_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7ed071]
~~~

Strange. But I can live with it. I'm closing this issue now. Thank you.
